SITL: add jsbsim_ext ("external JSBSim") model
GaloisInc/verse-ardupilot pull request #1
Opened 2024-09-13 21:11 UTC by spernsteiner

This branch adds a new aircraft model `jsbsim_ext` for the SITL simulator.  This is similar to the existing `jsbsim` model, but connects to an existing `jsbsim_proxy` process instead of starting JSBSim itself.  This allows JSBSim to run on a different machine from the SITL binary, which we need for the OpenSUT configuration.

The first commit adds the `jsbsim_ext` model as an exact copy of `jsbsim`, just renamed.  The second commit implements the new behavior.

Part of GaloisInc/verse-opensut#97

2024-09-24 17:14 UTC, podhrmic requested changes
Please push these changes into a new branch in https://github.com/galoisinc/ardupilot/

I opened an IT ticket to get you access, hopefully it will happen soon.

2024-09-24 17:46 UTC, spernsteiner commented
> Please push these changes into a new branch in https://github.com/galoisinc/ardupilot/

That's a public repo - did we finally get DISTAR approval for VERSE?  I haven't heard any update on that in a while

2024-09-24 18:38 UTC, podhrmic commented
~~Good point. Let me see.~~ You have write access to https://github.com/galoisinc/ardupilot/ now.

DISTAR is not ready yet, thus we will need to use this repo and move it over later.

2024-09-25 22:37 UTC, spernsteiner commented
> we will need to use this repo and move it over later.

Is this good to merge, then?

2024-09-25 22:45 UTC, podhrmic approved these changes

2024-09-25 22:45 UTC, podhrmic commented
Yes, just approved.

2024-09-25 23:24 UTC, merged